version: '3'

services: 
  server:
    build: ./src
    container_name: "server"
    restart: always
    ports:
      - 3000:3000
    links: 
      - mongo
    depends_on: 
      - mongo

  nginx:
    image: nginx:latest
    container_name: "nginx"
    restart: always
    ports:
      - "80:80"
    depends_on: 
      - server
    volumes: 
      - ./proxy/site.conf:/etc/nginx/conf.d/default.conf:cached

  mongo:
    image: mongo
    container_name: "mongo"
    restart: always
    command: 
      - mongod
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  mongo-data:
    image: busybox

volumes: 
  mongo-data: